import cadquery as cq

## FR4 attenae, green and yellow design

# Dimensions (in mm)
outer_radius = 0.3
height = 0.4
wall_thickness = 0.095

# cylinder to be placed around the rectangle supports
cyl = (
    cq.Workplane("XY")
    .circle(outer_radius)
    .extrude(height)
)

# Hollow it out with shell
cyl = (
    cyl.faces(">Z or <Z")  #faces positive Z dir and negative Z dir
    .shell(-wall_thickness) #shell out 1mm
)
## show_object(cyl)


## Dimensions (in mm)
width_c = 5
depth_c = 0.4
height_c = 0.8

connector =(
    cq.Workplane("XY")
    .box(height_c, width_c, depth_c)
    )
## show_object(connector)

antenna_assy_base = (
    cq.Assembly()
    .add(connector, name = "connector", color= cq.Color("gray"))
    .add(cyl, loc=cq.Location(0.65,-2.25,-0.2), name ="cylinder", color=cq.Color("gray"))
    .add(cyl, loc=cq.Location(-0.65, -2.25, -0.2), name = "cylinder2", color= cq.Color("gray"))
    )


show_object(antenna_assy_base)
