import cadquery as cq

## FR4 attenae, green and yellow design

import cadquery as cq


outer_radius = 1.1   
height = 4         

cyla = (
    cq.Workplane("XY")
    .circle(outer_radius)
    .extrude(height)
)

def make_arch_door(wall, length, width, height, floor_height):
    bottom = wall.faces("-Z").val()

    #initial box shape
    cutout = (cq.Workplane(bottom.Center())
              .box(length, width, height)
              .translate((0, 0, (height/2)+floor_height))
              )

    # fillet top edges to make archway
    cutout = cutout.faces("Z").edges("Y").fillet((length/2)-0.05)

    return wall.cut(cutout)


arch_length = outer_radius * 0.8      
arch_width = outer_radius * 2.2       
arch_height = height * 0.4            
floor_height = 0

cyl_with_tunnel = make_arch_door(cyla, arch_length, arch_width, arch_height, floor_height)

outer_radius2 = 0.3
height2 = 0.4
wall_thickness = 0.095

#
cyl = (
    cq.Workplane("XY")
    .circle(outer_radius2)
    .extrude(height2)
)

# hollow it out with shell
cyl = (
    cyl.faces(">Z or <Z")  #faces positive Z dir and negative Z dir
    .shell(-wall_thickness) #shell out 1mm
)
## show_object(cyl)



width_c = 5
depth_c = 0.4
height_c = 0.8

connector =(
    cq.Workplane("XY")
    .box(height_c, width_c, depth_c)
    )


## show_object(connector)

antenna_assy_base = (
    cq.Assembly()
    .add(connector, loc=cq.Location(0,-3.5,0), name = "connector", color= cq.Color("gray"))
    .add(cyl, loc=cq.Location(0.65,-5.75,-0.2), name ="cylinder", color=cq.Color("gray"))
    .add(cyl, loc=cq.Location(-0.65, -5.75, -0.2), name = "cylinder2", color= cq.Color("gray"))
    )

antenna_assy_base2 = (
    cq.Assembly()
    .add(connector, loc=cq.Location(0,3.5,0), name = "connector", color= cq.Color("gray"))
    .add(cyl, loc=cq.Location(0.65,5.75,-0.2), name ="cylinder", color=cq.Color("gray"))
    .add(cyl, loc=cq.Location(-0.65, 5.75, -0.2), name = "cylinder2", color= cq.Color("gray"))
    )

antenna_cylinder= (
    cq.Assembly()
    .add(cyl_with_tunnel, loc=cq.Location(cq.Vector(0,0,-0.2), cq.Vector(0,0,1), 45), name = "archcyl", color= cq.Color("gray"))
    )

show_object(antenna_cylinder)
show_object(antenna_assy_base)
show_object(antenna_assy_base2)

#duplicating the assembly to rotate it
final_assy = cq.Assembly()

# rotate 90 degrees about z axis
final_assy.add(antenna_assy_base, loc=cq.Location(cq.Vector(0,0,0), cq.Vector(0,0,1), 90), name="base_rotated1")

# rotate 90 degrees about z axis
final_assy.add(antenna_assy_base2, loc=cq.Location(cq.Vector(0,0,0), cq.Vector(0,0,1), 90), name="base_rotated2")

show_object(final_assy)
