import cadquery as cq


outer_radius = 1.8   
height = 4         

cyl = (
    cq.Workplane("XY")
    .circle(outer_radius)
    .extrude(height)
)

def make_arch_door(wall, length, width, height, floor_height):
    bottom = wall.faces("-Z").val()

    #initial box shape
    cutout = (cq.Workplane(bottom.Center())
              .box(length, width, height)
              .translate((0, 0, (height/2)+floor_height))
              )

    # fillet top edges to make archway
    cutout = cutout.faces("Z").edges("Y").fillet((length/2)-0.05)

    return wall.cut(cutout)


arch_length = outer_radius * 0.8      
arch_width = outer_radius * 2.2       
arch_height = height * 0.6            
floor_height = 0

cyl_with_tunnel = make_arch_door(cyl, arch_length, arch_width, arch_height, floor_height)

show_object(cyl_with_tunnel)
