import cadquery as cq

## FR4 attenae, green and yellow design


# --- Cylinder ---
outer_radius = 15
height = 50

cyl = (
    cq.Workplane("XY")
    .circle(outer_radius)
    .extrude(height)
)

# archway
def make_arch_door(wall, length, width, height, floor_height):
    bottom = wall.faces("-Z").val()

  # makes rectangle box
    cutout = (cq.Workplane(bottom.Center())
              .box(length, width, height)
              .translate((0, 0, (height/2)+floor_height))
              )

    # fillet to make arch
    cutout = cutout.faces("Z").edges("Y").fillet((length/2)-0.5)

    return wall.cut(cutout)

# arch dimensions TBD
arch_length = 10          
arch_width = outer_radius * 2.5   
arch_height = 12          
floor_height = 0         

cyl_with_tunnel = make_arch_door(cyl, arch_length, arch_width, arch_height, floor_height)

show_object(cyl_with_tunnel)
